openapi: 3.0.1
info:
  title: getCustomerInvoice
  description: Import from "functionInventory" Function App
  version: '1.0'
servers:
  - url: https://functioninventory-apim.azure-api.net/customerInvoice
paths:
  /get-item-individual:
    get:
      summary: item-individual
      description: item-individual
      operationId: get-get-item-individual
      parameters:
        - name: name
          in: query
          schema:
            type: ''
        - name: Ocp-Apim-Subscription-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'null'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]