openapi: 3.0.1
info:
  title: upload-info
  description: Import from "functionInventory" Function App
  version: '1.0'
servers:
  - url: https://functioninventory-apim.azure-api.net/functionInventory
paths:
  /get-db:
    post:
      summary: get-db
      operationId: post-get-db
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]